export { Packaton } from './src/app.js'
export { HtmlCompiler } from './src/plugins-prod/HtmlCompiler.js'
export { minifyHTML } from './src/plugins-prod/minifyHTML.js'
export { minifyCSS } from './src/plugins-prod/minifyCSS.js'
export { minifyJS } from './src/plugins-prod/minifyJS.js'
export { reportSizesPlugin } from './src/plugins-prod/reportSizesPlugin.js'
